name: dd_check_plugin
description: A flutter plugin for idea to listen to network requests
version: 3.1.5
homepage: https://github.com/mdddj/dd_check_plugin
environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=2.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  network_info_plus: ^4.1.0
  dio: ^5.4.0
  package_info_plus: ^5.0.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.2
  get_it: ^7.6.7
  logger: ^2.0.2+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  flutter_lints: ^3.0.1
  freezed: ^2.4.7
  json_serializable: ^6.7.1



flutter:
  plugin:
    platforms:
      android:
        package: shop.itbug.dd_check_plugin
        pluginClass: DdCheckPlugin
      ios:
        pluginClass: DdCheckPlugin
      macos:
        pluginClass: DdCheckPlugin
      windows:
        pluginClass: DdCheckPlugin
      web:
        pluginClass: DdCheckPluginWeb
        fileName: dd_check_plugin_web.dart

