name: dd_check_plugin
description: A flutter plugin for idea to listen to network requests
version: 4.0.0
homepage: https://github.com/mdddj/dd_check_plugin
environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  network_info_plus: ^6.1.4
  dio: ^5.8.0+1
  package_info_plus: ^8.3.0
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  shared_preferences: ^2.5.3
  get_it: ^8.0.3
  logger: ^2.5.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  freezed: ^3.0.6
  json_serializable: ^6.9.5


flutter:
  plugin:
    platforms:
      android:
        package: shop.itbug.dd_check_plugin
        pluginClass: DdCheckPlugin
      ios:
        pluginClass: DdCheckPlugin
      macos:
        pluginClass: DdCheckPlugin
      windows:
        pluginClass: DdCheckPlugin

