name: dd_check_plugin
description: A flutter plugin for idea to listen to network requests
version: 3.0.2
homepage: https://github.com/mdddj/dd_check_plugin
environment:
  sdk: ">=2.19.4 <4.0.0"
  flutter: ">=3.7.7"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  network_info_plus: ^4.1.0
  dio: ^5.3.3
  package_info: ^2.0.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  flutter_lints: ^2.0.3
  plugin_platform_interface: ^2.1.6
  shared_preferences: ^2.2.2
  get_it: ^7.6.4
  logger: ^2.0.2+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1

#dependency_overrides:
#  watcher: ^1.1.0


flutter:
  plugin:
    platforms:
      android:
        package: shop.itbug.dd_check_plugin
        pluginClass: DdCheckPlugin
      ios:
        pluginClass: DdCheckPlugin
      macos:
        pluginClass: DdCheckPlugin
      windows:
        pluginClass: DdCheckPlugin
      web:
        pluginClass: DdCheckPluginWeb
        fileName: dd_check_plugin_web.dart

