name: dd_check_plugin
description: A flutter plugin for idea to listen to network requests
version: 2.4.0
homepage: https://github.com/mdddj/dd_check_plugin
environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  network_info_plus: ^4.0.1
  dio: ^5.2.1+1
  package_info: ^2.0.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  flutter_lints: ^2.0.2
  plugin_platform_interface: ^2.1.4
  shared_preferences: ^2.2.0
  get_it: ^7.6.0
  logger: ^1.4.0
  flutter_web_plugins:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  freezed: ^2.3.5
  json_serializable: ^6.7.1



flutter:
  plugin:
    platforms:
      android:
        package: shop.itbug.dd_check_plugin
        pluginClass: DdCheckPlugin
      ios:
        pluginClass: DdCheckPlugin
      macos:
        pluginClass: DdCheckPlugin
      windows:
        pluginClass: DdCheckPlugin
      web:
        pluginClass: DdCheckPluginWeb
        fileName: dd_check_plugin_web.dart

