name: dd_check_plugin
description: A flutter plugin for idea to listen to network requests
version: 3.2.1
homepage: https://github.com/mdddj/dd_check_plugin
environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=2.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  network_info_plus: ^6.0.0
  dio: ^5.5.0+1
  package_info_plus: ^8.0.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  shared_preferences: ^2.2.3
  get_it: ^7.7.0
  logger: ^2.4.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.11
  flutter_lints: ^4.0.0
  freezed: ^2.5.7
  json_serializable: ^6.8.0

dependency_overrides: 
  meta: any

flutter:
  plugin:
    platforms:
      android:
        package: shop.itbug.dd_check_plugin
        pluginClass: DdCheckPlugin
      ios:
        pluginClass: DdCheckPlugin
      macos:
        pluginClass: DdCheckPlugin
      windows:
        pluginClass: DdCheckPlugin

